gui:
  timeFormat: "2006-01-02"
  shortTimeFormat: "15:04"
git:
  branchLogCmd: "git log --graph --oneline --decorate {{branchName}} --"
  log:
    showWholeGraph: false
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  allBranchesLogCmds:
    - git log --graph --oneline --decorate --all --date-order

